### ISSUE TITLE
Crash when shooting genetic animals mods animals

### ISSUE THREAD

**Issue by MrJakob99** [Stereowalker/C.O.M.B.A.T#100]
**Describe the bug**
[I can't attack the entitys from genetic animals, they just don't get damage although getting hit particles with crits. When shooting them with a bow, the game crashes.
Also the genetic animales entitiys lag around (stand still, mover very fast, stand still), which is not the case without the Combat installed]

**Logs**
[
[crash-2021-06-07_15.40.51-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T/files/6609424/crash-2021-06-07_15.40.51-server.txt)

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 6/7/21 3:40 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Can't find attribute combat:generic.physical_resistance
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233810_d_(AttributeModifierMap.java:21) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233804_a_(AttributeModifierMap.java:28) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(SourceFile:62) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1729) ~[?:?] {re:mixin,re:classloading,xf:fml:combat:living_entity_patch,pl:mixin:APP:combat.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70672_c(LivingEntity.java:3427) ~[?:?] {re:mixin,re:classloading,xf:fml:combat:living_entity_patch,pl:mixin:APP:combat.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1475) ~[?:?] {re:mixin,re:classloading,xf:fml:combat:living_entity_patch,pl:mixin:APP:combat.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?] {re:mixin,re:classloading,xf:fml:combat:living_entity_patch,pl:mixin:APP:combat.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.passive.AnimalEntity.func_70097_a(AnimalEntity.java:73) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,xf:fml:combat:server_world_patch}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,xf:fml:combat:server_world_patch}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233810_d_(AttributeModifierMap.java:21) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233804_a_(AttributeModifierMap.java:28) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(SourceFile:62) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1729) ~[?:?] {re:mixin,re:classloading,xf:fml:combat:living_entity_patch,pl:mixin:APP:combat.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70672_c(LivingEntity.java:3427) ~[?:?] {re:mixin,re:classloading,xf:fml:combat:living_entity_patch,pl:mixin:APP:combat.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1475) ~[?:?] {re:mixin,re:classloading,xf:fml:combat:living_entity_patch,pl:mixin:APP:combat.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?] {re:mixin,re:classloading,xf:fml:combat:living_entity_patch,pl:mixin:APP:combat.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.passive.AnimalEntity.func_70097_a(AnimalEntity.java:73) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,xf:fml:combat:server_world_patch}
-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.entity.projectile.ArrowEntity)
	Entity ID: 539
	Entity Name: Arrow
	Entity's Exact location: 140.57, 66.77, -90.71
	Entity's Block location: World: (140,66,-91), Chunk: (at 12,4,5 in 8,-6; contains blocks 128,0,-96 to 143,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 2.41, -1.14, 1.06
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,xf:fml:combat:server_world_patch}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Mr_Jakob99'/150, l='ServerLevel[BÖB]', x=125.66, y=71.24, z=-97.30]]
	Chunk stats: ServerChunkCache: 2263
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,64,-106), Chunk: (at 0,4,6 in 5,-7; contains blocks 80,0,-112 to 95,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 354 game time, 354 day time
	Level name: BÖB
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 19025 (now: false), thunder time: 118739 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-74-lowlatency
	Java Version: 1.8.0_292, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 5678888368 bytes (5415 MB) / 7247757312 bytes (6912 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx10240M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.24.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.24.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.24
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.24-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		GeneticAnimals-0_6_29.jar                         |Genetic Animals               |eanimod                       |0_6_29              |DONE      |Manifest: NOSIGNATURE
		Survive-1.16.5-3.3.1.jar                          |Survive                       |survive                       |1.16.5-3.3.1        |DONE      |Manifest: NOSIGNATURE
		UnionLib-1.16.5-3.3.2.jar                         |UnionLib                      |unionlib                      |3.3.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.24-universal.jar                |Forge                         |forge                         |36.1.24             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |Manifest: NOSIGNATURE
		C.O.M.B.A.T-1.16.5-7.3.1.jar                      |C.O.M.B.A.T                   |combat                        |7.3.0-beta          |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.0.98.jar                           |Just Enough Items             |jei                           |7.7.0.98            |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 75478a46-9f3d-450b-accb-3430d2c46d4b
	Player Count: 1 / 8; [ServerPlayerEntity['Mr_Jakob99'/150, l='ServerLevel[BÖB]', x=125.66, y=71.24, z=-97.30]]
	Data Packs: vanilla, mod:eanimod (incompatible), mod:survive (incompatible), mod:unionlib (incompatible), mod:forge, mod:torohealth, mod:curios, mod:combat, mod:jei
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Minecraft Environment:**
 - Forge Version: 36.1.24
 - UnionLib Version: 3.3.2
 - C.O.M.B.A.T Version: 7.3.0

**Additional context**
[The log also says something that the defence attribute can't be found.]

**Comment by Stereowalker** [comment]
[C.O.M.B.A.T-1.16.5-7.3.2-beta.zip](https://github.com/Stereowalker/C.O.M.B.A.T/files/6637266/C.O.M.B.A.T-1.16.5-7.3.2-beta.zip)
Run this to confirm if the issue is fixed

**Comment by MrJakob99** [comment]
Can confirm non of the issues above occur anymore. Good Job !
