### ISSUE TITLE
Forge Booting "load_registries" Error 

### ISSUE THREAD

**Issue by Jbird127** [Stereowalker/C.O.M.B.A.T#47]
Whenever I try to load up C.O.M.B.A.T., Forge runs into an error.

"C.O.M.B.A.T. (combat) encountered an error during the load_registries event phase
tried to access method"

Any help is greatly appreciated!

The part of the log that has to do with Combat is this:

[29Jun2020 08:34:51.470] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: tried to access method net.minecraft.village.PointOfInterestType.func_221042_a(Lnet/minecraft/block/Block;)Ljava/util/Set; from class com.stereowalker.combat.village.CPointOfInterestType[29Jun2020 08:34:51.470] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: tried to access method net.minecraft.village.PointOfInterestType.func_221042_a(Lnet/minecraft/block/Block;)Ljava/util/Set; from class com.stereowalker.combat.village.CPointOfInterestType Index: 22 Listeners: 0: NORMAL 1: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerParticles(Lnet/minecraftforge/event/RegistryEvent$Register;)V 2: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerFeatures(Lnet/minecraftforge/event/RegistryEvent$Register;)V 3: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerRecipeSerializers(Lnet/minecraftforge/event/RegistryEvent$Register;)V 4: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerBiomes(Lnet/minecraftforge/event/RegistryEvent$Register;)V 5: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V 6: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerBlocks(Lnet/minecraftforge/event/RegistryEvent$Register;)V 7: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerEnchantments(Lnet/minecraftforge/event/RegistryEvent$Register;)V 8: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerDimensions(Lnet/minecraftforge/event/RegistryEvent$Register;)V 9: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerDecorators(Lnet/minecraftforge/event/RegistryEvent$Register;)V 10: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerWorldCarvers(Lnet/minecraftforge/event/RegistryEvent$Register;)V 11: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerBiomeDecoratorTypes(Lnet/minecraftforge/event/RegistryEvent$Register;)V 12: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerSoundEvents(Lnet/minecraftforge/event/RegistryEvent$Register;)V 13: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerPaintings(Lnet/minecraftforge/event/RegistryEvent$Register;)V 14: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerDataSerializers(Lnet/minecraftforge/event/RegistryEvent$Register;)V 15: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerLeveledStats(Lnet/minecraftforge/event/RegistryEvent$Register;)V 16: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerProfessions(Lnet/minecraftforge/event/RegistryEvent$Register;)V 17: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerContainers(Lnet/minecraftforge/event/RegistryEvent$Register;)V 18: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerTileEntities(Lnet/minecraftforge/event/RegistryEvent$Register;)V 19: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerEffects(Lnet/minecraftforge/event/RegistryEvent$Register;)V 20: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerFluids(Lnet/minecraftforge/event/RegistryEvent$Register;)V 21: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerPotions(Lnet/minecraftforge/event/RegistryEvent$Register;)V 22: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerPOITypes(Lnet/minecraftforge/event/RegistryEvent$Register;)V 23: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerSpells(Lnet/minecraftforge/event/RegistryEvent$Register;)V 24: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerStats(Lnet/minecraftforge/event/RegistryEvent$Register;)V 25: ASM: class com.stereowalker.combat.registries.CombatRegistryEvents registerEntity(Lnet/minecraftforge/event/RegistryEvent$Register;)Vjava.lang.IllegalAccessError: tried to access method net.minecraft.village.PointOfInterestType.func_221042_a(Lnet/minecraft/block/Block;)Ljava/util/Set; from class com.stereowalker.combat.village.CPointOfInterestType at com.stereowalker.combat.village.CPointOfInterestType.<clinit>(CPointOfInterestType.java:18) at com.stereowalker.combat.registries.CombatRegistryEvents.registerPOITypes(CombatRegistryEvents.java:220) at net.minecraftforge.eventbus.ASMEventHandler_243_CombatRegistryEvents_registerPOITypes_Register.invoke(.dynamic) at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2215/2001568374.accept(Unknown Source) at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) at java.util.function.Consumer$$Lambda$2208/2002903874.accept(Unknown Source) at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) at java.util.function.Consumer$$Lambda$2208/2002903874.accept(Unknown Source) at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) at net.minecraftforge.fml.ModList$$Lambda$3308/721004015.accept(Unknown Source) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) at net.minecraftforge.fml.ModList$$Lambda$2178/383852959.dispatchEvent(Unknown Source) at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) at net.minecraftforge.fml.ModLoader$$Lambda$3335/527556644.accept(Unknown Source) at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:973) at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2062/483529787.run(Unknown Source) at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2063/286840121.run(Unknown Source) at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) at net.minecraft.client.main.Main.main(SourceFile:166) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/1269006535.call(Unknown Source) at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[29Jun2020 08:34:51.474] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:point_of_interest_type> dispatch for modid combatjava.lang.IllegalAccessError: tried to access method net.minecraft.village.PointOfInterestType.func_221042_a(Lnet/minecraft/block/Block;)Ljava/util/Set; from class com.stereowalker.combat.village.CPointOfInterestType at com.stereowalker.combat.village.CPointOfInterestType.<clinit>(CPointOfInterestType.java:18) ~[?:1.15.2-4.8.12] at com.stereowalker.combat.registries.CombatRegistryEvents.registerPOITypes(CombatRegistryEvents.java:220) ~[?:1.15.2-4.8.12] at net.minecraftforge.eventbus.ASMEventHandler_243_CombatRegistryEvents_registerPOITypes_Register.invoke(.dynamic) ~[?:?] at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) [?:31.2] at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$2215/2001568374.accept(Unknown Source) [?:31.2] at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51] at java.util.function.Consumer$$Lambda$2208/2002903874.accept(Unknown Source) [?:1.8.0_51] at java.util.function.Consumer.lambda$andThen$14(Consumer.java:65) [?:1.8.0_51] at java.util.function.Consumer$$Lambda$2208/2002903874.accept(Unknown Source) [?:1.8.0_51] at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) [?:?] at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$5(ModList.java:126) [?:?] at net.minecraftforge.fml.ModList$$Lambda$3308/721004015.accept(Unknown Source) [?:?] at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_51] at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_51] at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:126) [?:?] at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:96) [?:?] at net.minecraftforge.fml.ModList$$Lambda$2178/383852959.dispatchEvent(Unknown Source) [?:?] at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:71) [?:?] at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:214) [?:?] at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$25(ModLoader.java:206) [?:?] at net.minecraftforge.fml.ModLoader$$Lambda$3335/527556644.accept(Unknown Source) [?:?] at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:973) [?:?] at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:206) [?:?] at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) [?:?] at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2062/483529787.run(Unknown Source) [?:?] at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) [?:?] at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2063/286840121.run(Unknown Source) [?:?] at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?] at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) [?:?] at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2] at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/1269006535.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2] at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?][29Jun2020 08:34:51.478] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found[29Jun2020 08:34:51.478] [Render thread/FATAL] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: EventBus 0 shutting down - future events will not be posted.java.lang.Exception: stacktrace at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:278) [eventbus-2.2.0-service.jar:?] at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:115) [?:?] at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2063/286840121.run(Unknown Source) [?:?] at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) [?:?] at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) [?:?] at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2] at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/1269006535.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2] at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]

**Comment by Stereowalker** [comment]
Try upgrading forge to 31.2.21 and confirm if it's still an issue. If it still is, post your logs

**Comment by Jbird127** [comment]
That worked!  Thanks so much!

**Comment by Stereowalker** [comment]
You're welcome
