### ISSUE TITLE
[BUG] the mod will not load

### ISSUE THREAD

**Issue by llssc** [Stereowalker/C.O.M.B.A.T#65]
**Describe the bug**
The game kept crashing with COMBAT mod, so I initially thought it was a compatibility issue with some mod, but after testing the initial batch of mods, I decided to find out what is causing this error by removing other mods. 
I had to remove more and more mods, until the only remaining mod was the dependency and itself.

**Logs**
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 20. 10. 12 오후 8:53
Description: mouseClicked event handler

java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.compareNamespaced(Lnet/minecraft/util/ResourceLocation;)I
	at net.minecraftforge.event.RegistryEvent$MissingMappings$Mapping.compareTo(RegistryEvent.java:238) ~[?:?] {re:classloading}
	at net.minecraftforge.event.RegistryEvent$MissingMappings$Mapping.compareTo(RegistryEvent.java:167) ~[?:?] {re:classloading}
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52) ~[?:1.8.0_51] {}
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:1.8.0_51] {}
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351) ~[?:1.8.0_51] {}
	at java.util.TimSort.sort(TimSort.java:230) ~[?:1.8.0_51] {}
	at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_51] {}
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.GameData.lambda$null$31(GameData.java:730) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData$$Lambda$5605/1161564354.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.AdvancedLogMessageAdapter.formatTo(AdvancedLogMessageAdapter.java:60) ~[forge-1.16.3-34.1.19.jar:34.1] {}
	at org.apache.logging.log4j.core.pattern.MessagePatternConverter.format(MessagePatternConverter.java:123) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at net.minecrell.terminalconsole.MinecraftFormattingConverter.format(MinecraftFormattingConverter.java:133) ~[terminalconsoleappender-1.2.0.jar:?] {}
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.pattern.HighlightConverter.format(HighlightConverter.java:245) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:456) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:445) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:209) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:58) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:253) ~[terminalconsoleappender-1.2.0.jar:?] {}
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1991) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1835) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:776) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at net.minecraftforge.registries.GameData.lambda$injectSnapshot$35(GameData.java:728) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData$$Lambda$5600/582544112.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:718) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.FMLWorldPersistenceHook.readData(FMLWorldPersistenceHook.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.WorldPersistenceHooks.lambda$handleWorldDataLoad$1(WorldPersistenceHooks.java:45) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.WorldPersistenceHooks$$Lambda$5577/639922215.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.WorldPersistenceHooks.handleWorldDataLoad(WorldPersistenceHooks.java:45) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat.lambda$getReader$4(SaveFormat.java:202) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat$$Lambda$5503/961180560.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.storage.SaveFormat.func_237266_a_(SaveFormat.java:165) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat.access$400(SaveFormat.java:63) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237284_a_(SaveFormat.java:324) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.Minecraft.func_238181_a_(Minecraft.java:1622) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4712/962769430.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1810) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1661) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1631) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:259) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:292) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4666/1535571147.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4665/1966079203.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4084/1370756928.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.19.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/1596653154.call(Unknown Source) [forge-1.16.3-34.1.19.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.event.RegistryEvent$MissingMappings$Mapping.compareTo(RegistryEvent.java:238) ~[?:?] {re:classloading}
	at net.minecraftforge.event.RegistryEvent$MissingMappings$Mapping.compareTo(RegistryEvent.java:167) ~[?:?] {re:classloading}
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52) ~[?:1.8.0_51] {}
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:1.8.0_51] {}
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:351) ~[?:1.8.0_51] {}
	at java.util.TimSort.sort(TimSort.java:230) ~[?:1.8.0_51] {}
	at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_51] {}
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.GameData.lambda$null$31(GameData.java:730) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData$$Lambda$5605/1161564354.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.AdvancedLogMessageAdapter.formatTo(AdvancedLogMessageAdapter.java:60) ~[forge-1.16.3-34.1.19.jar:34.1] {}
	at org.apache.logging.log4j.core.pattern.MessagePatternConverter.format(MessagePatternConverter.java:123) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at net.minecrell.terminalconsole.MinecraftFormattingConverter.format(MinecraftFormattingConverter.java:133) ~[terminalconsoleappender-1.2.0.jar:?] {}
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.pattern.HighlightConverter.format(HighlightConverter.java:245) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:456) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSelectorSerializer.toSerializable(PatternLayout.java:445) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:209) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:58) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:253) ~[terminalconsoleappender-1.2.0.jar:?] {}
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) ~[log4j-core-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1991) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1835) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:776) ~[log4j-api-2.11.2.jar:2.11.2] {}
	at net.minecraftforge.registries.GameData.lambda$injectSnapshot$35(GameData.java:728) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.GameData$$Lambda$5600/582544112.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:718) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.FMLWorldPersistenceHook.readData(FMLWorldPersistenceHook.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.WorldPersistenceHooks.lambda$handleWorldDataLoad$1(WorldPersistenceHooks.java:45) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.WorldPersistenceHooks$$Lambda$5577/639922215.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.WorldPersistenceHooks.handleWorldDataLoad(WorldPersistenceHooks.java:45) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat.lambda$getReader$4(SaveFormat.java:202) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat$$Lambda$5503/961180560.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.storage.SaveFormat.func_237266_a_(SaveFormat.java:165) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat.access$400(SaveFormat.java:63) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237284_a_(SaveFormat.java:324) ~[?:?] {re:computing_frames,re:classloading}
	at net.minecraft.client.Minecraft.func_238181_a_(Minecraft.java:1622) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4712/962769430.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1810) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1661) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1631) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:259) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:292) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4666/1535571147.run(Unknown Source) ~[?:?] {}
-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.WorldSelectionScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4665/1966079203.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$4084/1370756928.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.19.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/1596653154.call(Unknown Source) [forge-1.16.3-34.1.19.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
https://i.imgur.com/hfnnnbf.png

**Minecraft Environment:**
 - Forge Version: 1.16.3-34.1.19
 - UnionLib Version: 1.16.3-3.0.0
 - C.O.M.B.A.T Version: 1.16.3-6.0.0

**Additional context**
[Add any other context about the problem here.]

**Comment by Stereowalker** [comment]
After looking at the log, I'm not really sure I can really pinpoint where the error is from. But to be sure when you did the compatibility check, was Optifine included in all of them? I'm asking because I can see Optifine in your screenshot

**Comment by llssc** [comment]
From time to time, trying to load a world that was testing other mods that I uninstalled would result in a crash as well, making me make a new world each time.

With COMBAT, however, the mod was crashing on client booting (with NoSuchMethod error), and when it finally ran after removing (I forgot when it started to run exactly) mods, it would still crash with NoSuchMethod error when I attempt to load a world.

I just tested again with just the mod and unionlib, even making a new world to remove the variable I stated on the first line, the client freezes when the world generation hits 100%, crashing the game.
Trying to load that ↑ world will freeze the client again, crashing the game.

A warning message pops up saying the world generation is trying to use an experimental feature, and I don't know if it is because of that, but the crash reports are of server rather than client.
![image](https://user-images.githubusercontent.com/69404048/96206930-d6ac8c80-0f1e-11eb-8931-586fd8860e8c.png)

Here is the crash report (third one, but I glanced the three reports and they all looked same).
[crash-2020-10-15_19.34.39-server.txt](https://github.com/Stereowalker/C.O.M.B.A.T/files/5388873/crash-2020-10-15_19.34.39-server.txt)

**Comment by llssc** [comment]
It seems the mod doesn't know what to do when a user tries to load a superflat world. The client behaves perfectly normal with loading default world generation. Would you take a look at the code and see what is confusing the mod?

Another thing, it seems it is incompatible with any mod that modifies "default" HUD or visuals, such as RPG HUD and **OptiFine**. With any of these two mods, the client will refuse to load the world. 
(HUD mod that adds non-default elements to the game such as Xaero's minimap/worldmap mod or inventory HUD will not cause problems) 

(this is only one of the bugs, since there is NoSuchMethodError on startup with unknown reason which I can't recreate anymore)

**Comment by Stereowalker** [comment]
Try updating the mod. The error should have seemed to stem from the dimension I added which I've removed.
