### ISSUE TITLE
Crash with fletching table (1.16.3 ; mod ver: 6.00)

### ISSUE THREAD

**Issue by TheAbyssalMimic** [Stereowalker/C.O.M.B.A.T#67]
**Describe the bug**
Crash whenever the players tries to interact with the fletching table (with possible world corruption)
**Logs**
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.item.crafting.RecipeBookStatus$CategoryStatus.func_242165_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.item.crafting.RecipeBookStatus.func_242151_a(SourceFile:75) ~[?:?] {re:classloading}
	at net.minecraft.item.crafting.RecipeBook.func_242142_a(SourceFile:75) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.recipebook.RecipeBookGui.func_191878_b(RecipeBookGui.java:147) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.stereowalker.combat.client.gui.screen.inventory.FletchingScreen.func_230430_a_(FletchingScreen.java:56) ~[?:1.16.3-6.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:281) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:491) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.23.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/2094115865.call(Unknown Source) [forge-1.16.3-34.1.23.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.item.crafting.RecipeBookStatus$CategoryStatus.func_242165_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.item.crafting.RecipeBookStatus.func_242151_a(SourceFile:75) ~[?:?] {re:classloading}
	at net.minecraft.item.crafting.RecipeBook.func_242142_a(SourceFile:75) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.recipebook.RecipeBookGui.func_191878_b(RecipeBookGui.java:147) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.stereowalker.combat.client.gui.screen.inventory.FletchingScreen.func_230430_a_(FletchingScreen.java:56) ~[?:1.16.3-6.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:281) ~[?:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: com.stereowalker.combat.client.gui.screen.inventory.FletchingScreen
	Mouse location: Scaled: (171, 128). Absolute: (512.000000, 384.000000)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['TheAbyssalMimic'/243, l='ClientLevel', x=-108.19, y=65.20, z=-129.73]]
	Chunk stats: Client Chunk Cache: 841, 552
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,64,-128), Chunk: (at 0,4,0 in -7,-8; contains blocks -112,0,-128 to -97,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 177 game time, 177 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1974) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:600) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.23.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/2094115865.call(Unknown Source) [forge-1.16.3-34.1.23.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

**To Reproduce**
Simply left click the fletching table

**Expected behavior**
------------------
**Screenshots**
------------------

**Minecraft Environment:**  
 - Forge Version:  34.1.23
 - UnionLib Version:  (1.16.3) 3.00
 - C.O.M.B.A.T Version: (1.16.3) 6.0.0

**Additional context**
The same thing causes sometimes (at least in a modpack) world corruption without ever interacting with the actual fletching table.

**Comment by Stereowalker** [comment]
I've fixed this in the latest update. Please check and confirm that there aren't any related errors. I'll close this issue if there's no reply within 2 days
