### ISSUE TITLE
Server load crash failed to load an item?

### ISSUE THREAD

**Issue by WheezerX** [Stereowalker/C.O.M.B.A.T#76]
Something to do with Orange Terracotta?

3:40:05 PM java.lang.NoSuchFieldError: ORANGE_TERRACOTTA
3:40:05 PM 	at com.stereowalker.combat.block.material.CMaterial.<clinit>(CMaterial.java:7) ~[combat:?] {re:classloading}
3:40:05 PM 	at com.stereowalker.combat.block.CBlocks.<clinit>(CBlocks.java:54) ~[combat:?] {re:classloading}
3:40:05 PM 	at com.stereowalker.combat.Combat.<clinit>(Combat.java:108) ~[combat:?] {re:classloading,pl:runtimedistcleaner:A}
3:40:05 PM 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
3:40:05 PM 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
3:40:05 PM 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:61) ~[forge:35.1] {re:classloading}
3:40:05 PM 	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source) ~[?:?] {}
3:40:05 PM 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
3:40:05 PM 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281] {}
3:40:05 PM 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:76) ~[forge:35.1] {re:classloading}
3:40:05 PM 	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:296) ~[forge:?] {re:classloading}
3:40:05 PM 	at net.minecraftforge.fml.ModLoader.lambda$buildMods$29(ModLoader.java:275) ~[forge:?] {re:classloading}
3:40:05 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:05 PM 	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
3:40:05 PM 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:05 PM 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:05 PM 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:277) ~[forge:?] {re:classloading}
3:40:06 PM 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[forge:?] {re:classloading}
3:40:06 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[forge:?] {re:classloading}
3:40:06 PM 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
3:40:06 PM 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
3:40:06 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
3:40:06 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:06 PM 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
3:40:06 PM 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
3:40:06 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
3:40:06 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
3:40:06 PM 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
3:40:06 PM 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
3:40:07 PM 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.37.jar:?] {}
3:40:07 PM 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.37.jar:?] {}
3:40:07 PM 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.37.jar:?] {}
3:40:07 PM [main/FATAL] [ne.mi.fm.ja.FMLJavaModLanguageProvider/LOADING]: Failed to build mod
3:40:07 PM java.lang.reflect.InvocationTargetException: null
3:40:07 PM 	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source) ~[?:?] {}
3:40:07 PM 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:76) ~[forge:35.1] {re:classloading}
3:40:07 PM 	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:296) ~[forge:?] {re:classloading}
3:40:07 PM 	at net.minecraftforge.fml.ModLoader.lambda$buildMods$29(ModLoader.java:275) ~[forge:?] {re:classloading}
3:40:07 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:277) ~[forge:?] {re:classloading}
3:40:07 PM 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[forge:?] {re:classloading}
3:40:07 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:07 PM 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[forge:?] {re:classloading}
3:40:08 PM 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
3:40:08 PM 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
3:40:08 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
3:40:08 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:08 PM 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
3:40:08 PM 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
3:40:08 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
3:40:08 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
3:40:08 PM 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
3:40:08 PM 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
3:40:08 PM 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.37.jar:?] {}
3:40:08 PM 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.37.jar:?] {}
3:40:08 PM 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.37.jar:?] {}
3:40:08 PM Caused by: net.minecraftforge.fml.ModLoadingException: C.O.M.B.A.T has class loading errors
3:40:08 PM ?7java.lang.NoSuchFieldError: ORANGE_TERRACOTTA
3:40:09 PM 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:67) ~[forge:35.1] {re:classloading}
3:40:09 PM 	... 39 more
3:40:09 PM Caused by: java.lang.NoSuchFieldError: ORANGE_TERRACOTTA
3:40:09 PM 	at com.stereowalker.combat.block.material.CMaterial.<clinit>(CMaterial.java:7) ~[combat:?] {re:classloading}
3:40:09 PM 	at com.stereowalker.combat.block.CBlocks.<clinit>(CBlocks.java:54) ~[combat:?] {re:classloading}
3:40:09 PM 	at com.stereowalker.combat.Combat.<clinit>(Combat.java:108) ~[combat:?] {re:classloading,pl:runtimedistcleaner:A}
3:40:09 PM 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
3:40:09 PM 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
3:40:09 PM 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:61) ~[forge:35.1] {re:classloading}
3:40:09 PM 	... 39 more
3:40:09 PM [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `edelwood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
3:40:09 PM [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `edelwood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
3:40:09 PM [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `cherrywood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
3:40:09 PM [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `cherrywood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
3:40:09 PM [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `mysterywood_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
3:40:09 PM [main/INFO] [ne.mi.re.GameData/]: Potentially Dangerous alternative prefix `forbidden_arcanus` for name `mysterywood_wall_sign`, expected `minecraft`. This could be a intended override, but in most cases indicates a broken mod.
3:40:09 PM [main/FATAL] [ne.mi.fm.ModLoader/CORE]: Failed to initialize mod containers
3:40:09 PM net.minecraftforge.fml.ModLoadingException: C.O.M.B.A.T has class loading errors
3:40:09 PM ?7java.lang.NoSuchFieldError: ORANGE_TERRACOTTA
3:40:09 PM 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:67) ~[forge:35.1] {re:classloading}
3:40:09 PM 	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source) ~[?:?] {}
3:40:09 PM 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:76) ~[forge:35.1] {re:classloading}
3:40:10 PM 	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:296) ~[forge:?] {re:classloading}
3:40:10 PM 	at net.minecraftforge.fml.ModLoader.lambda$buildMods$29(ModLoader.java:275) ~[forge:?] {re:classloading}
3:40:10 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:277) ~[forge:?] {re:classloading}
3:40:10 PM 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[forge:?] {re:classloading}
3:40:10 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
3:40:10 PM 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[forge:?] {re:classloading}
3:40:10 PM 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
3:40:10 PM 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
3:40:10 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
3:40:10 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:11 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:11 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:11 PM 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
3:40:11 PM 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
3:40:11 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
3:40:11 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
3:40:11 PM 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
3:40:11 PM 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
3:40:11 PM 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.37.jar:?] {}
3:40:11 PM 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.37.jar:?] {}
3:40:11 PM 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.37.jar:?] {}
3:40:11 PM Caused by: java.lang.NoSuchFieldError: ORANGE_TERRACOTTA
3:40:11 PM 	at com.stereowalker.combat.block.material.CMaterial.<clinit>(CMaterial.java:7) ~[combat:?] {re:classloading}
3:40:11 PM 	at com.stereowalker.combat.block.CBlocks.<clinit>(CBlocks.java:54) ~[combat:?] {re:classloading}
3:40:11 PM 	at com.stereowalker.combat.Combat.<clinit>(Combat.java:108) ~[combat:?] {re:classloading,pl:runtimedistcleaner:A}
3:40:11 PM 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
3:40:11 PM 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
3:40:11 PM 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:61) ~[forge:35.1] {re:classloading}
3:40:11 PM 	... 39 more
3:40:11 PM [main/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (16/18)
3:40:11 PM [main/FATAL] [ne.mi.fm.se.ServerModLoader/]: Crash report saved to .\crash-reports\crash-2021-02-05_15.40.09-fml.txt
3:40:11 PM ---- Minecraft Crash Report ----
3:40:11 PM // My bad.
3:40:11 PM Time: 2/5/21 3:40 PM
3:40:12 PM Description: Mod loading error has occurred
3:40:12 PM java.lang.Exception: Mod Loading has failed
3:40:12 PM 	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
3:40:12 PM 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
3:40:12 PM 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
3:40:12 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
3:40:12 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:12 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:12 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:12 PM 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
3:40:12 PM 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
3:40:12 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
3:40:12 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
3:40:12 PM 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
3:40:12 PM 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
3:40:12 PM 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.37.jar:?] {}
3:40:12 PM 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.37.jar:?] {}
3:40:12 PM 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.37.jar:?] {}
3:40:12 PM A detailed walkthrough of the error, its code path and all known details is as follows:
3:40:12 PM ---------------------------------------------------------------------------------------
3:40:12 PM -- Head --
3:40:12 PM Thread: main
3:40:12 PM Stacktrace:
3:40:12 PM 	at com.stereowalker.combat.block.material.CMaterial.<clinit>(CMaterial.java:7) ~[combat:?] {re:classloading}
3:40:12 PM -- MOD combat --
3:40:13 PM Details:
3:40:13 PM 	Mod File: C.O.M.B.A.T-1.16.5-7.1.1-deobf.jar
3:40:13 PM 	Failure message: C.O.M.B.A.T has class loading errors
3:40:13 PM 		java.lang.NoSuchFieldError: ORANGE_TERRACOTTA
3:40:13 PM 	Mod Version: 1.16.5-7.1.1
3:40:13 PM 	Mod Issue URL: https://github.com/Stereowalker/C.O.M.B.A.T./issues
3:40:13 PM 	Exception message: java.lang.NoSuchFieldError: ORANGE_TERRACOTTA
3:40:13 PM Stacktrace:
3:40:13 PM 	at com.stereowalker.combat.block.material.CMaterial.<clinit>(CMaterial.java:7) ~[combat:?] {re:classloading}
3:40:13 PM 	at com.stereowalker.combat.block.CBlocks.<clinit>(CBlocks.java:54) ~[combat:?] {re:classloading}
3:40:13 PM 	at com.stereowalker.combat.Combat.<clinit>(Combat.java:108) ~[combat:?] {re:classloading,pl:runtimedistcleaner:A}
3:40:13 PM 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
3:40:13 PM 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
3:40:13 PM 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:61) ~[forge:35.1] {re:classloading}
3:40:13 PM 	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source) ~[?:?] {}
3:40:13 PM 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
3:40:13 PM 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281] {}
3:40:13 PM 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:76) ~[forge:35.1] {re:classloading}
3:40:13 PM 	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:296) ~[forge:?] {re:classloading}
3:40:13 PM 	at net.minecraftforge.fml.ModLoader.lambda$buildMods$29(ModLoader.java:275) ~[forge:?] {re:classloading}
3:40:13 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:13 PM 	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
3:40:13 PM 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:13 PM 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:277) ~[forge:?] {re:classloading}
3:40:14 PM 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[forge:?] {re:classloading}
3:40:14 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[forge:?] {re:classloading}
3:40:14 PM 	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
3:40:14 PM 	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
3:40:14 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
3:40:14 PM 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
3:40:14 PM 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
3:40:14 PM 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
3:40:14 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
3:40:15 PM 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
3:40:15 PM 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
3:40:15 PM 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
3:40:15 PM 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.37.jar:?] {}
3:40:15 PM 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.37.jar:?] {}
3:40:15 PM 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.37.jar:?] {}

**Comment by Stereowalker** [comment]
What mods do you have loaded?
