### ISSUE TITLE
unionlib not loading on server

### ISSUE THREAD

**Issue by DeRp-MaSte5** [Stereowalker/C.O.M.B.A.T#80]
i have a server where I had survive and a lot of mods but union lib is giving an error at loading. this makes survive not able to be able to play. works on single-player, not on multiplayer

---- Minecraft Crash Report ----
// You're mean.

Time: 3/31/21, 1:32 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[mohist-1.16.5-439-server.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:66) [mohist-1.16.5-439-server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:63) [mohist-1.16.5-439-server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:60) [mohist-1.16.5-439-server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[mohist-1.16.5-439-server.jar:36.1] {}
-- MOD unionlib --
Details:
	Mod File: UnionLib-1.16.5-3.3.0.jar
	Failure message: UnionLib (unionlib) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 3.3.0
	Mod Issue URL: https://github.com/Stereowalker/C.O.M.B.A.T./issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[mohist-1.16.5-439-server.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
	at com.stereowalker.unionlib.UnionLib.<init>(UnionLib.java:79) ~[unionlib:3.3.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?] {}
	at java.lang.Class.newInstance(Class.java:584) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-70-generic
	Java Version: 11.0.10, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 540346368 bytes (515 MB) / 1124073472 bytes (1072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx3072M -Xms512M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/mohist-1.16.5-439-server.jar object_holder_definalize PLUGINSERVICE 
		/mohist-1.16.5-439-server.jar runtime_enum_extender PLUGINSERVICE 
		/mohist-1.16.5-439-server.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/mohist-1.16.5-439-server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/mohist-1.16.5-439-server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.3
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		CyclopsCore-1.16.5-1.11.3.jar                     |Cyclops Core                  |cyclopscore                   |1.11.3              |CREATE_REG|NOSIGNATURE
		pmmobridge-1.16.4-1.0.4.jar                       |PMMO Compatibility Mod        |pmmobridge                    |1.16.4-1.0.4        |CREATE_REG|NOSIGNATURE
		UnionLib-1.16.5-3.3.0.jar                         |UnionLib                      |unionlib                      |3.3.0               |ERROR     |NOSIGNATURE
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |CREATE_REG|NOSIGNATURE
		DoggyTalents-1.16.4-2.0.1.3.jar                   |Doggy Talents 2               |doggytalents                  |2.0.1.3             |CREATE_REG|NOSIGNATURE
		Industrial+Agriculture[Core]-1.16.3-1.7.1.jar     |Industrial Agriculture        |industrialagriculture         |1.16.3-1.7.1        |CREATE_REG|NOSIGNATURE
		IronJetpacks-1.16.4-4.2.0.jar                     |Iron Jetpacks                 |ironjetpacks                  |4.2.0               |CREATE_REG|NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |CREATE_REG|NOSIGNATURE
		ForgeEndertech-1.16.4-7.0.10.0-build.0037.jar     |Forge Endertech               |forgeendertech                |7.0.10.0            |CREATE_REG|NOSIGNATURE
		TerraForged-1.16.4-0.2.9.jar                      |TerraForged                   |terraforged                   |0.2.9               |CREATE_REG|7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |CREATE_REG|NOSIGNATURE
		citadel-1.6.2.jar                                 |Citadel                       |citadel                       |1.6.2               |CREATE_REG|NOSIGNATURE
		EvilCraft-1.16.5-1.1.0.jar                        |EvilCraft                     |evilcraft                     |1.1.0               |CREATE_REG|NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |CREATE_REG|NOSIGNATURE
		branders-spawnermod-1.16.4-1.7.10.jar             |Enhanced Mob Spawners         |spawnermod                    |1.7.10              |CREATE_REG|NOSIGNATURE
		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		toolleveling-1.16.2-1.1.1.jar                     |Tool Leveling                 |toolleveling                  |1.16.2 - 1.1.1      |CREATE_REG|NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |CREATE_REG|92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		ironshulkerboxes-1.16.4-5.1.11.jar                |Iron Shulker Boxes            |ironshulkerbox                |1.16.4-5.1.11       |CREATE_REG|NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |CREATE_REG|NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |CREATE_REG|NOSIGNATURE
		speedyhoppers-1.16.4-1.jar                        |Speedy Hoppers                |speedyhoppers                 |1.16.4-1            |CREATE_REG|NOSIGNATURE
		DeltaHardMode-1.16.3-1.1.1.jar                    |Delta Hard Mode               |deltahardmode                 |1.1.1               |CREATE_REG|NOSIGNATURE
		netherite-plus-mod-1.4.2-1.16.5-forge.jar         |Netherite Plus                |netherite_plus                |1.4.2-1.16.5        |CREATE_REG|NOSIGNATURE
		Upgraded+Netherite+1.16.4+-+1.8.1.jar             |Upgraded Netherite            |upgradednetherite             |1.7.0               |CREATE_REG|NOSIGNATURE
		ConfigurableCane-1.16.3-2.0.0.jar                 |Configurable Cane             |configurablecane              |2.0.0               |CREATE_REG|NOSIGNATURE
		PrettyPipes-1.9.2.jar                             |Pretty Pipes                  |prettypipes                   |1.9.2               |CREATE_REG|NOSIGNATURE
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |CREATE_REG|NOSIGNATURE
		customizableelytra-1.16.4-1.4.2.jar               |Customizable Elytra           |customizableelytra            |1.16.4-1.4.2        |CREATE_REG|NOSIGNATURE
		ResourcefulBees-1.16.5-0.6.5b.jar                 |Resourceful Bees              |resourcefulbees               |1.16.5-0.6.5b       |CREATE_REG|NOSIGNATURE
		[1.16.5]Gender-1.7.5.jar                          |Gender                        |gender                        |1.7.5               |CREATE_REG|NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |CREATE_REG|NOSIGNATURE
		BetterDrowning-1.16.5-2.0.2.jar                   |BetterDrowning                |betterdrowning                |2.0.2               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		EndRemastered-R36.jar                             |End Remastered 3.6            |endrem                        |1.16.3              |CREATE_REG|NOSIGNATURE
		dungeons_plus-1.16.4-1.1.3.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.3               |CREATE_REG|NOSIGNATURE
		SilentGear-1.16.3-2.6.6+226.jar                   |Silent Gear                   |silentgear                    |2.6.6+226           |CREATE_REG|NOSIGNATURE
		ElenaiDodge2-1.16.X-1.0.8b.jar                    |Elenai Dodge 2                |elenaidodge2                  |1.0.8b              |CREATE_REG|NOSIGNATURE
		Botania-1.16.4-411.jar                            |Botania                       |botania                       |1.16.4-411          |CREATE_REG|NOSIGNATURE
		EnchantingConvergence-1.16.5-1.0.0.jar            |Enchanting Convergence        |enchanting_convergence        |1.0.0               |CREATE_REG|NOSIGNATURE
		randomenchants-4.0.5.jar                          |Random Enchants               |randomenchants                |4.0.5               |CREATE_REG|NOSIGNATURE
		dpanvil-1.16.3-1.0.9.jar                          |DataPack Anvil                |dpanvil                       |1.16.3-1.0.9        |CREATE_REG|NOSIGNATURE
		curios-forge-1.16.5-4.0.4.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.4.0      |CREATE_REG|NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |CREATE_REG|NOSIGNATURE
		improved_genetics-0.7.1.jar                       |Improved Genetics             |improved_genetics             |v0.7.1              |CREATE_REG|NOSIGNATURE
		Survive-1.16.5-3.2.0.jar                          |Survive                       |survive                       |1.16.5-3.2.0        |CREATE_REG|NOSIGNATURE
		carrotslib-mc1.16.4-3.0b4.jar                     |Carrots Lib                   |carrots                       |3.0b4               |CREATE_REG|NOSIGNATURE
		tombstone-1.16-6.3.3.jar                          |Corail Tombstone              |tombstone                     |6.3.3               |CREATE_REG|NOSIGNATURE
		Chunk+Pregenerator-V1.16-3.0.5.jar                |Chunk Pregenerator            |chunkpregen                   |V1.16-3.0.5         |CREATE_REG|NOSIGNATURE
		Nugget's+Dungeons+II+v2.7.jar                     |Nugget's Dungeons II          |nuggets_dungeons_ii           |1.0.0               |CREATE_REG|NOSIGNATURE
		Project_MMO-1.16.4-3.48.jar                       |Project MMO                   |pmmo                          |1.16.4-3.48         |CREATE_REG|NOSIGNATURE
		architectury-1.10.138-forge.jar                   |Architectury                  |architectury                  |1.10.138            |CREATE_REG|NOSIGNATURE
		ftb-gui-library-1605.2.1.40-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.40         |CREATE_REG|NOSIGNATURE
		the_bumblezone-1.16.5-2.2.14.jar                  |The Bumblezone                |the_bumblezone                |1.16.5-2.2.14       |CREATE_REG|NOSIGNATURE
		BetterBurning-1.16.5-6.0.2.jar                    |BetterBurning                 |betterburning                 |6.0.2               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BetterMineshafts-Forge-1.16.4-2.0.2.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.2        |CREATE_REG|NOSIGNATURE
		geckolib-forge-1.16.5-3.0.14.jar                  |GeckoLib                      |geckolib3                     |3.0.14              |CREATE_REG|NOSIGNATURE
		SaveMyStronghold-1.16.4-1.0.jar                   |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          |CREATE_REG|NOSIGNATURE
		Cursed-1.16.5-7.0.1.jar                           |Cursed                        |cursed                        |7.0.1               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Cucumber-1.16.4-4.1.8.jar                         |Cucumber Library              |cucumber                      |4.1.8               |CREATE_REG|NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |CREATE_REG|NOSIGNATURE
		elementalcraft-1.16.4-2.5.12.jar                  |ElementalCraft                |elementalcraft                |1.16.4-2.5.12       |CREATE_REG|NOSIGNATURE
		Druidcraft-1.16.5-0.4.52.jar                      |Druidcraft                    |druidcraft                    |0.4.52              |CREATE_REG|NOSIGNATURE
		FunMod+5.1.jar                                    |Fun Mod                       |funmod                        |5.1                 |CREATE_REG|NOSIGNATURE
		abnormals_core-1.16.5-3.1.1.jar                   |Abnormals Core                |abnormals_core                |3.1.1               |CREATE_REG|NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |CREATE_REG|NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.0.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.0      |CREATE_REG|NOSIGNATURE
		colytra-forge-1.16.4-5.1.0.0.jar                  |Colytra                       |colytra                       |1.16.4-5.1.0.0      |CREATE_REG|NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |CREATE_REG|NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |CREATE_REG|NOSIGNATURE
		Waystones_1.16.5-7.4.0.jar                        |Waystones                     |waystones                     |7.4.0               |CREATE_REG|NOSIGNATURE
		BetterPortals-1.16.4-0.3.2.jar                    |YUNG's Better Portals         |betterportals                 |1.16.4-0.3.2        |CREATE_REG|NOSIGNATURE
		EpicFightMod-1.16.5-3.0.4.jar                     |Epic Fight Mod                |epicfight                     |1.0                 |CREATE_REG|NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |CREATE_REG|NOSIGNATURE
		OuterEnd-0.2.8.jar                                |Outer End                     |outer_end                     |0.2.4               |CREATE_REG|NOSIGNATURE
		BasicNetherOres-1.16.5-5.5.0.jar                  |Basic Nether Ores             |bno                           |5.5.0               |CREATE_REG|NOSIGNATURE
		champions-forge-1.16.5-2.0.1.5.jar                |Champions                     |champions                     |1.16.5-2.0.1.5      |CREATE_REG|NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |CREATE_REG|NOSIGNATURE
		creeperconfetti-3.5.jar                           |Creeper Confetti              |creeperconfetti               |3.5                 |CREATE_REG|NOSIGNATURE
		starlight-forge-0.0.3.jar                         |Starlight                     |starlight                     |0.0.3               |CREATE_REG|NOSIGNATURE
		immersive-portals-0.16-mc1.16.5-forge.jar         |Immersive Portals             |immersive_portals             |0.14                |CREATE_REG|NOSIGNATURE
		ars_nouveau-1.16.4-1.11.5.jar                     |Ars Nouveau                   |ars_nouveau                   |1.11.5              |CREATE_REG|NOSIGNATURE
		firstaid-1.9.6.jar                                |First Aid                     |firstaid                      |1.9.6               |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.1.3-universal.jar                 |Forge                         |forge                         |36.1.3              |CREATE_REG|NOSIGNATURE
		Ceramics-1.16.5-1.6.2.jar                         |Ceramics                      |ceramics                      |1.6.2               |CREATE_REG|NOSIGNATURE
		MysticalAgriculture-1.16.4-4.1.5.jar              |Mystical Agriculture          |mysticalagriculture           |4.1.5               |CREATE_REG|NOSIGNATURE
		MysticalAgradditions-1.16.4-4.1.4.jar             |Mystical Agradditions         |mysticalagradditions          |4.1.4               |CREATE_REG|NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.1.3-server.jar                    |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |CREATE_REG|NOSIGNATURE
		Enchantment-Descriptions-1_16_5.jar               |EnchantmentDescriptions       |enchdesc                      |7.0.2               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		SilentLib-1.16.3-4.9.2+65.jar                     |Silent Lib                    |silentlib                     |4.9.2+65            |CREATE_REG|NOSIGNATURE
		HerdMentality-1.16.5-6.0.1.jar                    |HerdMentality                 |herdmentality                 |6.0.1               |CREATE_REG|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		AdLods-1.16.4-4.1.3.0-build.0034.jar              |Large Ore Deposits            |adlods                        |4.1.3.0             |CREATE_REG|NOSIGNATURE
		NETHER_BETTER.jar                                 |Nether_betterMOD              |nether_bettermod              |1.0.0               |CREATE_REG|NOSIGNATURE
		GeneticAnimals-0_6_23.jar                         |Genetic Animals               |eanimod                       |0_6_23              |CREATE_REG|NOSIGNATURE
		armorunder-mc1.16.4-2.0b10.jar                    |Armor Underwear               |armorunder                    |2.0b10              |CREATE_REG|NOSIGNATURE
		Mantle-1.16.5-1.6.79.jar                          |Mantle                        |mantle                        |1.6.79              |CREATE_REG|NOSIGNATURE
		rats-7.1.1-1.16.5.jar                             |Rats                          |rats                          |7.1.1               |CREATE_REG|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |CREATE_REG|NOSIGNATURE
		Quark-r2.4-308.jar                                |Quark                         |quark                         |r2.4-308            |CREATE_REG|NOSIGNATURE
		Apotheosis-1.16.3-4.4.1.jar                       |Apotheosis                    |apotheosis                    |4.4.1               |CREATE_REG|NOSIGNATURE
		OfflineSkins-1.16.5-v1a.jar                       |OfflineSkins                  |offlineskins                  |1.16.5-v1a          |CREATE_REG|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		thedragonlib-1.16.3-1.1.0.jar                     |TheDragonLib                  |thedragonlib                  |1.16.3-1.1.0        |CREATE_REG|NOSIGNATURE
		armorplus-1.16.5-16.3.1.jar                       |ArmorPlus                     |armorplus                     |1.16.5-16.3.1       |CREATE_REG|NOSIGNATURE
		enhancedcelestials-1.0.2-1.16.4.jar               |Enhanced Celestials           |enhancedcelestials            |1.0.2-1.16.4        |CREATE_REG|NOSIGNATURE
		byg-1.1.14.jar                                    |Oh The Biomes You'll Go       |byg                           |1.1.14              |CREATE_REG|NOSIGNATURE
		SilentGems-1.16.3-3.7.11+114.jar                  |Silent's Gems 3               |silentgems                    |3.7.11+114          |CREATE_REG|NOSIGNATURE
		Industrial+Agriculture[Mekanism]-1.16.3-1.7.1.jar |Industrial Agriculture Plugin-|iapmekanism                   |1.16.3-1.7.1        |CREATE_REG|NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v1b.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v1b          |CREATE_REG|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		Cyan+Warrior+Swords+Mod+3.1-RC1+(1.16.5).jar      |Cyan Warrior Swords Mod       |cwsr                          |3.1.0.0             |CREATE_REG|NOSIGNATURE
		better_respawn-1.16.5-1.0.0.jar                   |Better Respawn                |better_respawn                |1.16.5-1.0.0        |CREATE_REG|NOSIGNATURE
		xptome-1.16.5-v2.1.jar                            |XP Tome                       |xpbook                        |v2.1                |CREATE_REG|NOSIGNATURE
		farlanders-1.16.4-1.3.8.jar                       |The Farlanders                |farlanders                    |1.3.8               |CREATE_REG|NOSIGNATURE
	Crash Report UUID: 3e185576-c7e9-4e54-acdf-7e72daeebf02
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs

**Comment by Stereowalker** [comment]
I've addressed this issue in the latest version of UnionLib, but you're going to have to wait a while before I update C.O.M.B.A.T. to support that version
