### ISSUE TITLE
[BUG] java.lang.NoSuchMethodError: com.stereowalker.unionlib.util.EntityHelper.registerAttributes

### ISSUE THREAD

**Issue by LemADEC** [Stereowalker/C.O.M.B.A.T#81]
**Describe the bug**
Game fails to load the mod

**Logs**
```
-- Head --
Thread: Render thread
Stacktrace:
	at com.stereowalker.combat.Combat.lambda$setup$3(Combat.java:168) ~[?:1.16.5-7.1.2] {re:classloading}
-- MOD combat --
Details:
	Mod File: C.O.M.B.A.T-1.16.5-7.1.2.jar
	Failure message: C.O.M.B.A.T (combat) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: com.stereowalker.unionlib.util.EntityHelper.registerAttributes(Lnet/minecraft/entity/EntityType;Ljava/util/function/Consumer;)V
	Mod Version: 1.16.5-7.1.2
	Mod Issue URL: https://github.com/Stereowalker/C.O.M.B.A.T./issues
	Exception message: java.lang.NoSuchMethodError: com.stereowalker.unionlib.util.EntityHelper.registerAttributes(Lnet/minecraft/entity/EntityType;Ljava/util/function/Consumer;)V
Stacktrace:
	at com.stereowalker.combat.Combat.lambda$setup$3(Combat.java:168) ~[?:1.16.5-7.1.2] {re:classloading}
	at com.stereowalker.combat.Combat$$Lambda$8402/241830402.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at com.stereowalker.combat.Combat.setup(Combat.java:166) ~[?:1.16.5-7.1.2] {re:classloading}
	at com.stereowalker.combat.Combat$$Lambda$3829/431294276.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
```

**To Reproduce**
1. boot the game

**Expected behavior**
Game actually loading

**Minecraft Environment:**
 - Forge Version: 36.1.4
 - UnionLib Version: 1.16.5-3.3.0
 - C.O.M.B.A.T Version: 1.16.5-7.1.2

**Comment by Stereowalker** [comment]
Update to the latest version of C.O.M.B.A.T.
