### ISSUE TITLE
[BUG] Game crashes when casting (I guess) a projectile spell

### ISSUE THREAD

**Issue by MrJakob99** [Stereowalker/C.O.M.B.A.T#84]
**Describe the bug**
[When using an elemental spell which should shoot a projectile the game crashes, tried it with Rock Shot and Fire Bolt.
You charge it up -> freeze -> crash]

**Logs**
[---- Minecraft Crash Report ----
// But it works on my machine.

Time: 4/19/21 1:41 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.nbt.NBTUtil.func_186860_b(SourceFile:167) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT.func_186857_a(CompoundNBT.java:133) ~[?:?] {re:classloading,re:mixin}
	at com.stereowalker.combat.api.spell.SpellInstance.read(SpellInstance.java:77) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.SpellEntity.getSpell(SpellEntity.java:47) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.SpellEntity.getHitSound(SpellEntity.java:52) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.AbstractMagicProjectileEntity.<init>(AbstractMagicProjectileEntity.java:61) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.AbstractMagicProjectileEntity.<init>(AbstractMagicProjectileEntity.java:70) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.AbstractMagicProjectileEntity.<init>(AbstractMagicProjectileEntity.java:75) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.SpellEntity.<init>(SpellEntity.java:27) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.api.spell.AbstractProjectileSpell.spellProgram(AbstractProjectileSpell.java:24) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.api.spell.SpellInstance.executeSpell(SpellInstance.java:82) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.item.AbstractMagicCastingItem.func_77615_a(AbstractMagicCastingItem.java:140) ~[combat:1.16.5-7.2.1] {re:classloading}
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:453) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forge:filled_map.4,xf:fml:unionlib:item_stack_patch,xf:fml:forge:itemstack}
	at net.minecraft.entity.LivingEntity.func_184597_cx(LivingEntity.java:2870) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:combat:living_entity_patch,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:combat:living_entity_patch}
	at net.minecraft.client.multiplayer.PlayerController.func_78766_c(PlayerController.java:409) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.2.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.nbt.NBTUtil.func_186860_b(SourceFile:167) ~[?:?] {re:classloading}
	at net.minecraft.nbt.CompoundNBT.func_186857_a(CompoundNBT.java:133) ~[?:?] {re:classloading,re:mixin}
	at com.stereowalker.combat.api.spell.SpellInstance.read(SpellInstance.java:77) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.SpellEntity.getSpell(SpellEntity.java:47) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.SpellEntity.getHitSound(SpellEntity.java:52) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.AbstractMagicProjectileEntity.<init>(AbstractMagicProjectileEntity.java:61) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.AbstractMagicProjectileEntity.<init>(AbstractMagicProjectileEntity.java:70) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.AbstractMagicProjectileEntity.<init>(AbstractMagicProjectileEntity.java:75) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.entity.projectile.SpellEntity.<init>(SpellEntity.java:27) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.api.spell.AbstractProjectileSpell.spellProgram(AbstractProjectileSpell.java:24) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.api.spell.SpellInstance.executeSpell(SpellInstance.java:82) ~[combat:1.16.5-7.2.1] {re:classloading}
	at com.stereowalker.combat.item.AbstractMagicCastingItem.func_77615_a(AbstractMagicCastingItem.java:140) ~[combat:1.16.5-7.2.1] {re:classloading}
	at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:453) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:forge:filled_map.4,xf:fml:unionlib:item_stack_patch,xf:fml:forge:itemstack}
	at net.minecraft.entity.LivingEntity.func_184597_cx(LivingEntity.java:2870) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:combat:living_entity_patch,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:combat:living_entity_patch}
	at net.minecraft.client.multiplayer.PlayerController.func_78766_c(PlayerController.java:409) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Mr_Jakob99'/277, l='ClientLevel', x=-255.03, y=68.00, z=10.10]]
	Chunk stats: Client Chunk Cache: 441, 272
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,63,52), Chunk: (at 0,3,4 in -16,3; contains blocks -256,0,48 to -241,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5349 game time, 5349 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.2.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.4.0-71-lowlatency
	Java Version: 1.8.0_282, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 775839584 bytes (739 MB) / 2147483648 bytes (2048 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:-OmitStackTraceInFastThrow -Xms512M -Xmx10240M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xss1M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.2
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |NOSIGNATURE
		physics-mod-1.3.4_forge.jar                       |Physics Mod                   |physicsmod                    |1.0                 |DONE      |NOSIGNATURE
		ItemPhysicLite_v1.4.6_mc1.16.2.jar                |ItemPhysic Lite               |itemphysiclite                |1.4.0               |DONE      |NOSIGNATURE
		UnionLib-1.16.5-3.3.1.jar                         |UnionLib                      |unionlib                      |3.3.1               |DONE      |NOSIGNATURE
		ElenaiDodge-1.16.2-1.7.2.jar                      |Elenai Dodge                  |elenaidodge                   |1.16.2-1.7.2        |DONE      |NOSIGNATURE
		C.O.M.B.A.T-1.16.5-7.2.1.jar                      |C.O.M.B.A.T                   |combat                        |1.16.5-7.2.1        |DONE      |NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.70.jar                           |Just Enough Items             |jei                           |7.6.1.70            |DONE      |NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |NOSIGNATURE
		GeneticAnimals-0_6_29.jar                         |Genetic Animals               |eanimod                       |0_6_29              |DONE      |NOSIGNATURE
		FpsReducer-mc1.16.4-1.18.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.4-1.18       |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.2-universal.jar                 |Forge                         |forge                         |36.1.2              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		curios-forge-1.16.4-4.0.3.3.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.3      |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.1.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.1      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		EnhancedVisuals_v1.3.24_mc1.16.5.jar              |EnhancedVisuals               |enhancedvisuals               |1.3.0               |DONE      |NOSIGNATURE
	Crash Report UUID: 8faa68bb-6b18-4bc7-b1bc-032627691105
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.39, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible), file/Quark Programmer Art.zip, file/Enhanced+Audio+r3.zip, file/BetterSounds+v1.2.zip, file/1.1.0_AnimatedEntities.zip (incompatible), file/SpawnEgg3D.zip (incompatible), file/Crops-3D_MC1.14.4_v1.0.0.zip (incompatible), file/nature-plus-v2-1-16-4-by-erlemo.zip (incompatible), file/nature-plus-sleet-addon.zip (incompatible), file/AVPBR-1-3.zip, file/UltimaCraft_PBR_(pre.8_fix.1).zip, file/UltimaCraft_Mobs_Default_(pre.8).zip, file/Motschens_Better_Leaves.zip, file/UltimaCraft_(pre.8_fix2).zip, file/Luminous1.1.zip, file/FreshAnimations_v1.2.zip, file/FreshAnimations_v1.2_Addons.zip
	Current Language: Deutsch (Deutschland)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210219-144623
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_3.12.zip
	OpenGlVersion: 4.6.0 NVIDIA 460.39
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
[crash-2021-04-19_13.41.13-client.txt](https://github.com/Stereowalker/C.O.M.B.A.T/files/6335804/crash-2021-04-19_13.41.13-client.txt)
]

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Minecraft Environment:**
 - Forge Version: 36.1.2
 - UnionLib Version: 3.3.1
 - C.O.M.B.A.T Version: 7.2.1

**Additional context**
[Tried it  some with many mod and than again with less mods. Same outcome.
I can just guess that the problem are projectile spells, because both fire bolt and rock shot sound like it uses the same methode. Also casting ring of fire worked, though it did no damage, but maybe it shouldn't even do that. I'm new to the mod so yeah]

**Comment by NerdetteNut** [comment]
Got this one too, both with and without optifine.

**Comment by MrJakob99** [comment]
With the new update? It should be fixed by now....

**Comment by Stereowalker** [comment]
I've fixed it so it should be working now
