### ISSUE TITLE
Description- "Mod combat only supports curios 4.0.1.0 or above Currently, curios is 1.16.5-4.0.5.1"  I dont get the problem, since it seems that the 4.0.5.1 should be considered above.   If anyone can help, thank you in advance[BUG]

### ISSUE THREAD

**Issue by Jasonthenonhuman** [Stereowalker/C.O.M.B.A.T#86]
**Describe the bug**
"Mod combat only supports curios 4.0.1.0 or above
Currently, curios is 1.16.5-4.0.5.1"

**Logs**
[08:31:37] [main/INFO]: ModLauncher running: args [--username, --version, forge-36.1.16, --gameDir, C:\Users\maste\curseforge\minecraft\Instances\The Ultimate Modpack (1) (1), --assetsDir, C:\Users\maste\curseforge\minecraft\Install\assets, --assetIndex, 1.16, --uuid, c318c51b379047a19f1d72cf09e46b67, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.16, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[08:31:37] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[08:31:37] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[08:31:37] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[08:31:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/maste/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[08:31:41] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-36.1.16, --gameDir, C:\Users\maste\curseforge\minecraft\Instances\The Ultimate Modpack (1) (1), --assetsDir, C:\Users\maste\curseforge\minecraft\Install\assets, --uuid, c318c51b379047a19f1d72cf09e46b67, --username, MindfulPlague63, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[08:31:50] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08:31:51] [Render thread/INFO]: Setting user: MindfulPlague63
[08:31:51] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[08:31:55] [Render thread/FATAL]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §ecombat§r only supports §3curios§r §o4.0.1.0 or above§r
§7Currently, §3curios§r§7 is §o1.16.5-4.0.5.1
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:64) ~[?:?]
	at net.minecraftforge.fml.ModLoadingException$$Lambda$2867/1134237170.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:114) ~[?:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:148) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:103) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2864/1977508673.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:123) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2865/1947666055.run(Unknown Source) [?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:103) [?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$420/552416003.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[08:31:55] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[08:31:55] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[08:31:55] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[08:31:56] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state
[08:31:56] [Render thread/INFO]: Narrator library for x64 successfully loaded
[08:31:56] [Render thread/INFO]: Reloading ResourceManager: Default
[08:31:57] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelRegistryEvent to a broken mod state
[08:31:57] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:00] [Worker-Main-6/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:01] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:02] [Worker-Main-7/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:04] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:04] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:04] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:04] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:04] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:04] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[08:32:04] [Render thread/INFO]: OpenAL initialized.
[08:32:04] [Render thread/INFO]: Sound engine started
[08:32:05] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[08:32:05] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:05] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[08:32:05] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[08:32:05] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:05] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[08:32:05] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:05] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[08:32:05] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[08:32:05] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:05] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[08:32:05] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:06] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelBakeEvent to a broken mod state
[08:32:06] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[08:32:06] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:06] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[08:32:06] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:06] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[08:32:06] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[08:32:06] [Render thread/INFO]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (23/26)
[08:32:06] [Render thread/FATAL]: Crash report saved to C:\Users\maste\curseforge\minecraft\Instances\The Ultimate Modpack (1) (1)\crash-reports\crash-2021-05-02_08.32.06-fml.txt

**To Reproduce**
[Steps to reproduce the behavior:
1. Create a Modpack Profile
2. Add the C.O.M.B.A.T. mod, the latest version, and the Curios mod, the latest version, for 1.16.5
3. Click play and be lead to the minecraft launcher
4. Play the modpack
5. [See Error]

**Expected behavior**
I expected the game to run with the mod due to the version being compatible

**Screenshots**
![image](https://user-images.githubusercontent.com/83542920/116815529-91028a80-ab23-11eb-831b-65211b542ba5.png)
![image](https://user-images.githubusercontent.com/83542920/116815540-a24b9700-ab23-11eb-8d32-ee216ce12916.png)
![image](https://user-images.githubusercontent.com/83542920/116815561-b55e6700-ab23-11eb-9e17-458902b80a46.png)

**Minecraft Environment:**
 - Forge Version: 36.1.16
 - UnionLib Version: 1.16.5- 3.3.2.jar
 - C.O.M.B.A.T Version: 1.16.5-7.2.1.jar

**Comment by Stereowalker** [comment]
This is an issue with the latest versions of forge. I'll soon be uploading a fix for this

**Comment by Stereowalker** [comment]
Fixed
