### ISSUE TITLE
[BUG] Crashes on startup.

### ISSUE THREAD

**Issue by Jwellison** [Stereowalker/C.O.M.B.A.T#95]
**Describe the bug**
Crashes on start up. I tried a new instance of Forge  36.1.23 with just this mod and it's dependencies. I think from the log it is a failed injection for the sword block feature.

**Logs**
[22May2021 10:56:37.822] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Mega_Helmet, --version, 1.16.5, --gameDir, C:\_gdl\instances\TestLand, --assetsDir, C:\_gdl\datastore\assets, --assetIndex, 1.16, --uuid, c2096f55e34747acaa2e1b2343c8f9ac, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.23, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[22May2021 10:56:37.825] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_242 by AdoptOpenJDK
[22May2021 10:56:38.141] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[22May2021 10:56:38.181] [main/INFO] [mixin/]: SpogePowered MIXIN Subsystem Version=0.8.2 ource=file:/C:/_gdl/datastore/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[22May2021 10:56:38.221] [main/WARN] [net.minecraftforge.fml.loading.FMLConfig/CORE]: Configuration file C:\_gdl\instances\TestLand\config\fml.toml is not correct. Correcting
[22May2021 10:56:38.227] [main/WARN] [net.minecraftforge.fml.loading.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[22May2021 10:56:40.705] [main/ERROR] [mixin/]: Mixin config unionlib.mixins.json does not specify "minVersion" property
[22May2021 10:56:40.708] [main/ERROR] [mixin/]: Mixin config combat.mixins.json does not specify "minVersion" property
[22May2021 10:56:40.711] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, C:\_gdl\instances\TestLand, --assetsDir, C:\_gdl\datastore\assets, --uuid, c2096f55e34747acaa2e1b2343c8f9ac, --username, Mega_Helmet, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 854, --height, 480]
[22May2021 10:56:42.247] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[22May2021 10:56:42.248] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[22May2021 10:56:42.248] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[22May2021 10:56:42.248] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[22May2021 10:56:42.248] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[22May2021 10:56:42.248] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[22May2021 10:56:42.249] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[22May2021 10:56:42.249] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22May2021 10:56:42.249] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22May2021 10:56:42.249] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22May2021 10:56:42.249] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22May2021 10:56:42.249] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[22May2021 10:56:42.250] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[22May2021 10:56:42.250] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[22May2021 10:56:42.250] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[22May2021 10:56:42.250] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[22May2021 10:56:42.251] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[22May2021 10:56:42.251] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:644]: 	... 10 more
[22May2021 10:56:42.251] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[22May2021 10:56:42.251] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[22May2021 10:56:42.251] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[22May2021 10:56:42.252] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[22May2021 10:56:42.252] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[22May2021 10:56:42.252] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[22May2021 10:56:42.252] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[22May2021 10:56:42.252] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[22May2021 10:56:42.252] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[22May2021 10:56:42.252] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[22May2021 10:56:42.252] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[22May2021 10:56:42.253] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[22May2021 10:56:42.253] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[22May2021 10:56:42.253] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
[22May2021 10:56:42.253] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[22May2021 10:56:42.253] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[22May2021 10:56:42.253] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[22May2021 10:56:42.254] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)
[22May2021 10:56:42.254] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[22May2021 10:56:42.254] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[22May2021 10:56:42.254] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[22May2021 10:56:42.254] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[22May2021 10:56:42.254] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[22May2021 10:56:42.254] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[22May2021 10:56:42.255] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[22May2021 10:56:42.255] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[22May2021 10:56:42.255] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[22May2021 10:56:42.255] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22May2021 10:56:42.255] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22May2021 10:56:42.255] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22May2021 10:56:42.255] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22May2021 10:56:42.256] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:668]: 	at java.lang.Thread.run(Thread.java:748)
[22May2021 10:56:42.256] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method blockWithSword(F)F in combat.mixins.json:LivingEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap combat.refmap.json
[22May2021 10:56:42.256] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[22May2021 10:56:42.256] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[22May2021 10:56:42.256] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[22May2021 10:56:42.257] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[22May2021 10:56:42.257] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[22May2021 10:56:42.257] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[22May2021 10:56:42.257] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[22May2021 10:56:42.257] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[22May2021 10:56:42.257] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:710]: 	... 30 more

**To Reproduce**
[Steps to reproduce the behavior:
4. See error]

**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Minecraft Environment:**
 - Forge Version: 
 - UnionLib Version: 
 - C.O.M.B.A.T Version: 

**Additional context**
[Add any other context about the problem here.]

**Comment by Stereowalker** [comment]
I get the bug, but did you run this with only COMBAT? If you ran only this mod and didn't get this error, then there is an incompatibility between this mod and some other mod that you have installed.

**Comment by Jwellison** [comment]
COMBAT 7.3
JEI 7.7.0.99
UnionLib 3.3.2
Forge 36.1.23

These mods only and I get the crash on boot. Gets partially through booting up MC and crashes.

**Comment by Lyj4n** [comment]
for some reason the latest COMBAT version crashes the game when combined with other mods, I'm downgrading the 7.2.4 for now til this bug is fixed since I never faced this issue on the previous version.

here's a part of my log:
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method blockWithSword(F)F in combat.mixins.json:LivingEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap combat.refmap.json

UPDATE: i downgraded to 7.2.4 and now my game works
