### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ESOJM3** [Stereowalker/C.O.M.B.A.T#96]
**Describe the bug**
So when I download COMBAT it says "Error 0" and it only happends with the mod, I made a profile where I only downloaded the mod and the same error pop out. I has been like this since Saturday.

**Screenshots**
I sent them in Discord because I don't know how to do it here
**Minecraft Environment:**
 - Forge Version: Forge 36.1.16
 - UnionLib Version: 1.16.5
 - C.O.M.B.A.T Version: 1.16.5

**Comment by Stereowalker** [comment]
I need the crash log

**Comment by ESOJM3** [comment]
Crash log: An unexpected error issue occurred and the game crashed. Exit Code: 0

**Comment by Stereowalker** [comment]
not exactly what I meant. First, run the game and get it to crash again, then in your game folder, enter the log folder and send the debug.log file

**Comment by ESOJM3** [comment]
![Screenshot 2021-05-26 213319](https://user-images.githubusercontent.com/84813020/119757172-2dd9ee80-be6a-11eb-9a88-321ba951f274.png)
So I clicked on "logs" and then what do I choose? (Sorry, I don't know to much about it D:)

**Comment by Stereowalker** [comment]
if there isnt a debug.log file, send the latest.log file

**Comment by ESOJM3** [comment]
I clicked in "latest" 
a[21:30:11] [main/INFO]: ModLauncher running: args [--username, ESOJM3, --version, forge-36.1.16, --gameDir, C:\Users\jmanu\curseforge\minecraft\Instances\Mano, --assetsDir, C:\Users\jmanu\curseforge\minecraft\Install\assets, --assetIndex, 1.16, --uuid, d6a7bddd2cd94a27b0e490796896ad96, --accessToken, ????????, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 36.1.16, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[21:30:11] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[21:30:11] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[21:30:13] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[21:30:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/jmanu/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[21:30:18] [main/ERROR]: Mixin config unionlib.mixins.json does not specify "minVersion" property
[21:30:18] [main/ERROR]: Mixin config combat.mixins.json does not specify "minVersion" property
[21:30:18] [main/INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[21:30:18] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-36.1.16, --gameDir, C:\Users\jmanu\curseforge\minecraft\Instances\Mano, --assetsDir, C:\Users\jmanu\curseforge\minecraft\Install\assets, --uuid, d6a7bddd2cd94a27b0e490796896ad96, --username, ESOJM3, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[21:30:19] [main/INFO]: Patching LivingEntity#attackEntityFrom
[21:30:19] [main/INFO]: Patching LivingEntity#blockUsingShield
[21:30:19] [main/INFO]: Patching LivingEntity#applyPotionDamageCalculations
[21:30:19] [main/INFO]: Patching Item#getItemEnchantability
[21:30:20] [main/INFO]: Patching RepairContainer#updateRepairOutput
[21:30:20] [main/INFO]: Successfully removed the anvil level cap.
[21:30:20] [main/INFO]: Patching RepairContainer#updateRepairOutput
[21:30:20] [main/INFO]: Successfully allowed nbt-unbreakable items in the anvil.
[21:30:20] [main/INFO]: Patching net/minecraft/inventory/container/RepairContainer
[21:30:20] [main/INFO]: Patching ModelBakery#<init>
[21:30:20] [main/INFO]: Patching AnvilScreen#drawGuiContainerForegroundLayer
[21:30:21] [pool-3-thread-1/INFO]: Patching Item#getItemEnchantability
[21:30:22] [pool-3-thread-1/INFO]: Patching ItemStack#onItemUse
[21:30:23] [pool-3-thread-1/INFO]: Patching SharedMonsterAttributes#readAttributeModifier
[21:30:23] [pool-3-thread-1/INFO]: Patching LivingEntity#attackEntityFrom
[21:30:23] [pool-3-thread-1/INFO]: Patching LivingEntity#blockUsingShield
[21:30:23] [pool-3-thread-1/INFO]: Patching LivingEntity#applyPotionDamageCalculations
[21:30:23] [pool-3-thread-1/INFO]: Patching EnchantmentHelper#getEnchantmentModifierDamage
[21:30:23] [pool-3-thread-1/INFO]: Patching EnchantmentHelper#getModifierForCreature
[21:30:23] [pool-3-thread-1/INFO]: Patching EnchantmentHelper#applyThornEnchantments
[21:30:23] [pool-3-thread-1/INFO]: Patching EnchantmentHelper#applyArthropodEnchantments
[21:30:24] [pool-3-thread-1/INFO]: Patching buildEnchantmentList for the Enchantability affix.
[21:30:24] [pool-3-thread-1/INFO]: Patching EnchantmentHelper#getEnchantmentDatas
[21:30:24] [pool-3-thread-1/INFO]: Patching CombatRules#getDamageAfterMagicAbsorb
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$481/1241976048.call(Unknown Source)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:30:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$644/1432304085.get(Unknown Source)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$652/1464377080.accept(Unknown Source)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$590/583593544.run(Unknown Source)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:30:24] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method blockWithSword(F)F in combat.mixins.json:LivingEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap combat.refmap.json
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[21:30:24] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 33 more

**Comment by ESOJM3** [comment]
So I click in "latest" right?

**Comment by Stereowalker** [comment]
thanks, I can see the issue

**Comment by ESOJM3** [comment]
So, I don't send anything else right?

**Comment by JosephGallagher2001** [comment]
> thanks, I can see the issue

May I ask what the issue is? I'm just curious, hehe.
